spring.application.name=Login

server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/MiniProject
spring.datasource.username=root
spring.datasource.password=News@123
spring.datasource.driver-class-name=com.mysql.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=karthikraj7474@gmail.com
spring.mail.password=jyufovzkednpqqav
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

project.messages.regSucc=Your Registration is Success
project.messages.emailExist=Email Already exist
project.messages.emailNull=Email cannot be null or empty
project.messages.passCreated=New password Got Created
project.messages.wrongTempPass=Wrong temp password
project.messages.emailNotFound=Email not found
project.messages.tempSent=TempPassword sent to your registered mail
project.messages.login=Login Success
project.messages.wrongPass=Wrong Password
project.messages.idNotFound=Id not found
project.messages.idFound=Record Got Deleted
project.messages.inactive=Login Successfull but Account not activated yet
